version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    container_name: app
    restart: on-failure
    networks:
      - app-net
  postgres:
    image: "postgres:14.2-alpine"
    container_name: app_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=esp32
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
  redis:
    image: "redis:6.2-alpine"
    container_name: app_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-net

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-net:
    driver: bridge